export enum UserActionTypes {
  SET_USER_DATA = "SET_USER_DATA",
  // SET_FOREIGN_USER_DATA="SET_FOREIGN_USER_DATA",
  LOGOUT_USER = "LOGOUT_USER",
  // SET_APP_LOADING="SET_APP_LOADING",
  // SET_FOREIGN_USER_LOADING="SET_FOREIGN_USER_LOADING",
  // SET_USER_ERROR="SET_USER_ERROR",
  // SET_IS_FOLLOWED="SET_IS_FOLLOWED",
  // SET_USER_FOLLOWS="SET_USER_FOLLOWS",
  // SET_IS_FOLLOWED_ON_SUBS="SET_IS_FOLLOWED_ON_SUBS"
}
