const statusCodes = {
  EMPTY_FIELD: 'EMPTY_FIELD',
  USER_ALREADY_EXIST: 'USER_ALREADY_EXIST',
  MISSING_AUTHORIZATION_HEADER: 'MISSING_AUTHORIZATION_HEADER',
  BAD_TOKEN: 'BAD_TOKEN',
  WRONG_ROLE: 'WRONG_ROLE',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  WRONG_TOKEN: 'WRONG_TOKEN',
  BAD_DATA: 'BAD_DATA',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  CANT_GET_YOURSELF: 'CANT_GET_YOURSELF',
  REPORT_ALREADY_EXIST: 'REPORT_ALREADY_EXIST',
};
export default statusCodes;
